textos = {
    "Español": {
        "titulo": " Detector de Phishing / Spam con IA",
        "instruccion": "Escribe o pega el texto de un email o mensaje para analizar si es legítimo o phishing.",
        "mensaje": "📩 Mensaje:",
        "boton": "Analizar",
        "advertencia_vacio": "Por favor, escribe un mensaje para analizar.",
        "mensaje_legitimo": "✅ El mensaje parece legítimo.",
        "mensaje_phishing": "🚨 El mensaje parece ser phishing o spam.",
        "confianza": "🔎 Confianza del modelo:",
        "palabras_clave": "### 🧠 Palabras clave encontradas:",
        "no_claves": "No se encontraron palabras clave sospechosas.",
        "explicacion_ia": "### 💬 Explicación con IA:",
        "explicacion_generada": "Explicación generada con IA:",
        "error_openai": "⚠️ No se pudo obtener la explicación de IA.",
        "verificacion_urls": "### 🔗 Verificación de enlaces:",
        "urls_maliciosas": "Se detectaron enlaces maliciosos:",
        "urls_seguras": "No se detectaron enlaces peligrosos con Google Safe Browsing.\n⚠️ **Importante:** Esto no garantiza que el enlace sea seguro. Solo significa que actualmente **no aparece en la lista de URLs maliciosas de Google.**"
    },
    "English": {
        "titulo": " Phishing / Spam Detector with AI",
        "instruccion": "Paste the content of an email or message to analyze if it is legitimate or phishing.",
        "mensaje": "📩 Message:",
        "boton": "Analyze",
        "advertencia_vacio": "Please enter a message to analyze.",
        "mensaje_legitimo": "✅ The message appears to be legitimate.",
        "mensaje_phishing": "🚨 The message appears to be phishing or spam.",
        "confianza": "🔎 Model confidence:",
        "palabras_clave": "### 🧠 Detected keywords:",
        "no_claves": "No suspicious keywords found.",
        "explicacion_ia": "### 💬 Explanation by AI:",
        "explicacion_generada": "Explanation generated by AI:",
        "error_openai": "⚠️ Could not get AI explanation.",
        "verificacion_urls": "### 🔗 URL Verification:",
        "urls_maliciosas": "Malicious links detected:",
        "urls_seguras": "No dangerous URLs detected with Google Safe Browsing.\n⚠️ **Important:** This does not guarantee the link is safe. It only means it currently **does not appear on Google's malicious URLs list.**"
    }
}
